const StartupIndustries = [
  "Artificial Intelligence (AI)",
  "Agritech",
  "Biotech",
  "Clean Energy",
  "Consumer Electronics",
  "Cybersecurity",
  "Edtech",
  "E-commerce",
  "Fintech",
  "Foodtech",
  "Gaming",
  "Healthcare",
  "Insurtech",
  "Logistics and Supply Chain",
  "Medtech",
  "Mobile Apps",
  "Real Estate Tech (Proptech)",
  "Remote Work Tools",
  "Robotics",
  "Social Media and Networking",
  "Software as a Service (SaaS)",
  "Space Tech",
  "Travel and Tourism",
  "Wearable Technology",
  "Web3 and Blockchain",
];

export default StartupIndustries;
